author: 'kei-g'
branding:
  color: 'blue'
  icon: 'upload'
description: 'Patches description and overview to DockerHub'
inputs:
  description:
    description: Single-line description of your docker image
    required: true
  overview:
    description: >
      Full-text description of your docker image.
      If not specified, a content of README.md in your repository alternates.
    required: false
  password:
    description: Your password on DockerHub
    required: true
  repo:
    description: Repository name of your docker image
    required: true
  username:
    description: Your name on DockerHub
    required: true
name: 'DockerHub Patcher'
outputs:
  response:
    description: The response from DockerHub
runs:
  main: 'dist/bin/patch.js'
  using: 'node16'
