jobs:
  build:
    name: Build on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - name: Build
        run: npm run build
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22
name: Build
on:
  push:
    branches:
      - main
