jobs:
  coverage:
    name: Check code coverages on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - name: Test
        run: npm test
      - name: Archive code coverages report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverages-report-${{ github.event.repository.name }}-${{ matrix.node }}
          path: |
            coverage
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
          - 20
name: Coverage
on:
  push:
    branches:
      - main
