jobs:
  coverage:
    if: github.ref_type == 'branch'
    name: Check code coverages on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - name: Test
        run: |
          export DOCKERHUB_PASSWORD="${{ secrets.DOCKERHUB_PASSWORD }}"
          export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          npm test
      - name: Archive code coverages report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverages-report-${{ github.repository.name }}-${{ matrix.node }}
          path: |
            coverage
    strategy:
      fail-fast: false
      matrix:
        node:
          - '12'
          - '14'
          - '16'
          - '17'
name: Coverage
on:
  pull_request:
  push:
